### ISSUE TITLE
Crash When Hovering Over Tarot Cards in JEI 0.65-alpha

### ISSUE THREAD

**Issue by AceTheEldritchKing** [shiroroku/TarotCards#1]
I booted up the alpha from CurseForge to play around with. I looked up the cards in JEI, and upon hovering over one of them my game crashed leaving an exception error. The crash log should be attached to here but please let me know if you need any more info.

[crash-2022-09-10_20.10.29-client.txt](https://github.com/shiroroku/TarotCards/files/9541578/crash-2022-09-10_20.10.29-client.txt)

**Comment by shiroroku** [comment]
`cannot be cast to class io.github.apace100.apoli.util.PowerGrantingItem`

this seems like a bug coming from apace100.apoli.util.StackPowerUtil.getPowers, i'm not sure what mod it is but you might wanna check with them. i use jei in my dev environment so i can confirm it doesnt crash when hovering

**Comment by AceTheEldritchKing** [comment]
Alright! I'll check it out, thank you for clarifying!

**Comment by shiroroku** [comment]
did a little more messing around and i think i found issue, ill see if i can fix it today. has to do with the tarot decks item and other mods that modify tooltips and stuff i believe

**Comment by shiroroku** [comment]
https://github.com/shiroroku/TarotCards/commit/436615dbad8b0e6508c08d5bbc4164b879172abd

newest version (0.7) should fix the crash, lemme know if it doesnt
