### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by DaoHuang1** [shiroroku/TarotCards#11]
Can you apply the effects of Tarot: Magician to the golden knife in Farmer's Delight and the machete in Nether's Delight?

**Comment by shiroroku** [comment]
you can already do this with a datapack, simply add "farmersdelight:golden_knife" (or any golden item) to the "tarotcards:items/golden" tag. other tags can be located [here](https://github.com/shiroroku/TarotCards/tree/master/src/main/resources/data/tarotcards/tags/items).

for more info you can check out [datapack with tags](https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack#Tags).
