### ISSUE TITLE
The World Tarot Card does not respect PVP setting

### ISSUE THREAD

**Issue by maxhenkes** [shiroroku/TarotCards#14]
**Mod version:**
tarotcards-1.20-1.5.5.jar

**Describe the issue:**
The World tarot card applies the slow to any player in radius on a server with pvp off. Very annoying.

**Additional info:**
It's been a few years since I've created mods but it appears your isAllied check here doesn't cover other players in a PVE setting. I've built the project locally and filtering for players in PVE removes the slowness debuff, so this seems to be the culprit. 

https://github.com/shiroroku/TarotCards/blob/556581b3d442bfeaca216e132ac58c7b7a84265c/src/main/java/shiroroku/tarotcards/Item/Tarot/TheWorldTarot.java#L28

**Comment by shiroroku** [comment]
ty, i didnt realize that pvp played a part in it, fix coming soon
