### ISSUE TITLE
Moon Card Error

### ISSUE THREAD

**Issue by ThatHobro** [shiroroku/TarotCards#15]
**Mod version:** Current 1.20-1.5.7

**Describe the issue:** The moon card times out too quickly to maintain its effect, creating a distracting flicker.

**How to Reproduce:**
1. Go to game
2. Equip Moon card
3. See error

**Additional info:**
Add any other info about the problem here.

**Comment by ThatHobro** [comment]
Discovered the issue. If you have underwater night vision as an effect from another item active, it interferes with the Moon effect.

**Comment by shiroroku** [comment]
what effect is underwater night vision?

**Comment by ThatHobro** [comment]
Enigmatic Legacy provides an item that gives vision underwater but not above water.
