### ISSUE TITLE
Tarot Deck item crashes when open

### ISSUE THREAD

**Issue by PandoraPanther** [shiroroku/TarotCards#16]
Mod version: 1.6.1

Issue: While playing the game with my wife i made her a Tarot Deck for the card she found and when i right clicked it to open it the game crashed

Process:
1:Joined world and created the tarot deck

2:Right clicked to try and view interface. 

3:Game kicked wife and crashed me

I recreated the crash again in the same world but without LAN being active by doing the steps again. Crash Log included

[crash-2024-02-26_06.22.44-server.txt](https://github.com/shiroroku/TarotCards/files/14403875/crash-2024-02-26_06.22.44-server.txt)

**Comment by shiroroku** [comment]
you seem to be using the 1.20 tarot cards on 1.20.4 which is incompatible

tarot cards 1.20.4 and beyond is only for neoforge
