### ISSUE TITLE
Game crashes when Pillager attacks

### ISSUE THREAD

**Issue by HoodBlah** [shiroroku/TarotCards#2]
Whenever a Pillager attacks the game crashes. I did extensive testing with my modpack and tarot cards is unfortunately the root cause. I really hope you can fix this as this is one of the best mods I have stumbled upon.
[latest.log](https://github.com/shiroroku/TarotCards/files/9592043/latest.log)

**Comment by shiroroku** [comment]
https://github.com/shiroroku/TarotCards/commit/01891c05fc548a7392c12384fae2da0054febfdf

new version 0.71 should be out on curseforge soon with fix
