### ISSUE TITLE
Unable to find "The Devil"

### ISSUE THREAD

**Issue by KajesLorian** [shiroroku/TarotCards#3]
Minecraft 1.18.2
TarotCards 0.71-Alpha

I'm using the lootr mod, so there have been several opportunities on my server for all seven of us to find it, but no luck so far (we have multiple of each of the other cards).

**Comment by shiroroku** [comment]
https://github.com/shiroroku/TarotCards/commit/8528fb66b8f1e5625e72754c4a2a7a83c97b84cd
