### ISSUE TITLE
Tarotcards: hermit's configuration file does not work

### ISSUE THREAD

**Issue by spake404** [shiroroku/TarotCards#5]
No matter how much armor you configure to give, the actual armor value you get is always 10.
![Jdk-17 0 5 Screenshot 2023 01 29 - 14 34 04 46](https://user-images.githubusercontent.com/123435269/215309526-881c0ff6-837d-4268-b15a-24fc64c5679b.png)
![Jdk-17 0 5 Screenshot 2023 01 29 - 14 34 09 03](https://user-images.githubusercontent.com/123435269/215309528-fde6b18a-3109-4475-a244-0043c9293dcc.png)

**Comment by shiroroku** [comment]
this is because for some cards you need to restart the game after changing the config

ill look into a way to refreshing the config without restarting the game soon

**Comment by spake404** [comment]
Try to exit the game and reopen the game. The config remains unchanged. I have tried many times

**Comment by shiroroku** [comment]
please post your config file

**Comment by spake404** [comment]
> please post your config file
here you are  [tarotcards-common.txt](https://github.com/shiroroku/TarotCards/files/10608789/tarotcards-common.txt)

Attached with a screenshot that does not work when using this config file to start t
![1eb1f45580466c2c01775600fbcf60e](https://user-images.githubusercontent.com/123435269/216771576-b69b725a-bec3-4252-96b8-970da19a2a49.png)
he game

**Comment by shiroroku** [comment]
looks like this only happens in 1.18.2, ill fix soon
also it seems like this applies to other attribute based tarots like the chariot and the sun?

**Comment by shiroroku** [comment]
https://github.com/shiroroku/TarotCards/commit/2c630ff6e1a80fada907a907fe59241fc4c838c9

finally got around to a fix, new version 1.2.5 for 1.18.2 will be out soon
