### ISSUE TITLE
Justice Tarot Card Crash

### ISSUE THREAD

**Issue by Orangejewce92** [shiroroku/TarotCards#6]
*Before submitting a bug please double check you are playing the latest release versions, and that this issue has not been submitted by someone else before, thank you.*

**Mod version:tarotcards-1.18.2-1.0-release.jar]**

**Describe the issue: Ticking Entity Crash**
heres a snippit of the tick crash. thank you
[https://pastebin.com/gFxEeAvM](url)

**Comment by shiroroku** [comment]
i cant reproduce this crash in dev. are you doing something with a firework rocket or have a mod that modifies them?

**Comment by Orangejewce92** [comment]
No mod that modifies them. Unsure how the player was specifically causing the crash. But it happened 3 times in a row, all with the same crash. 
I'd have to get more specifics I suppose.
Thanks for the speedy reply.

**Comment by Orangejewce92** [comment]
i had another crash from the Justice card

**Comment by Orangejewce92** [comment]
[https://pastebin.com/QDrEmUqf](url)

**Comment by Orangejewce92** [comment]
Also if two users have the Justice card and attack each other the server will crash.

**Comment by DrGrego** [comment]
Same happend on our server, one of the players had justice card and was fighting guardians, i don't know full details but can attach crash report

**Comment by Bigbangataque** [comment]
Replying to the previous comment, that was me. I was just swimming, towards an underground temple. Engaged with the normal guardian, didnt seem to have any special effect on them. There was the laser particles, and after a few seconds, got disconnected and server crashed. I have Tarot Deck with Justice on the first slot, no other card.

**Comment by DrGrego** [comment]
https://pastebin.com/uFD8W0iB
that's only a part of crash report, full report is 2mb in size

**Comment by shiroroku** [comment]
i think i found the issue, ill try to put an update out today

**Comment by shiroroku** [comment]
[tarotcards-1.18.2-testfix.zip](https://github.com/shiroroku/TarotCards/files/10818577/tarotcards-1.18.2-testfix.zip)
im still not able to reproduce the crash, but heres a build that should fix the bug. let me know if it works then ill publish it to curseforge.

**Comment by DrGrego** [comment]
> [tarotcards-1.18.2-testfix.zip](https://github.com/shiroroku/TarotCards/files/10818577/tarotcards-1.18.2-testfix.zip) im still not able to reproduce the crash, but heres a build that should fix the bug. let me know if it works then ill publish it to curseforge.

This should be installed on both client and server or it can be used only on server side?

**Comment by shiroroku** [comment]
on both

**Comment by DrGrego** [comment]
> on both

Ok thanks for info

**Comment by Orangejewce92** [comment]
Mm yes on both. But can we test with mismatch versions ? So can I add this test fix to my server ? And still use current ?

**Comment by shiroroku** [comment]
> Mm yes on both. But can we test with mismatch versions ? So can I add this test fix to my server ? And still use current ?

you could just have it server side but it could cause some weird things to happen & possibly crash. the test fix is just the 1.18.2 1.0 version with the fix. its not compatible with the 1.19.2 if thats what you mean.

if it works on 1.18.2 then i can fix 1.19.2 the same way and then put them both up on curseforge

**Comment by Orangejewce92** [comment]
So equip the justice card. and go to an Ocean Monument. you will crash instantly with the justice card being the issue.

**Comment by Orangejewce92** [comment]
Can confirm the Test build you have here works.
Sorry for taking so long

**Comment by shiroroku** [comment]
thank you, ill try to get out the update in a few days once im off work

**Comment by Orangejewce92** [comment]
Any update on release?

**Comment by shiroroku** [comment]
https://github.com/shiroroku/TarotCards/commit/0946556f09c3f85a7ef9c49283ed320b800d2fed

soon hopefully
