### ISSUE TITLE
[Mod Interaction] High Priestess card not upgrading enchanted books to the level specified by Apotheosis

### ISSUE THREAD

**Issue by PyroBurnem** [shiroroku/TarotCards#7]
**Mod version:**
1.18.2-1.0

**Describe the issue:**
Apotheosis is a mod that changes the maximum level an enchantment can have. With it installed, using the High Priestess card to upgrade enchantments only respects vanilla limits and not the new limits imposed by Apotheosis.

**How to Reproduce:**
1. Install Apotheosis (and prerequisites). Highest enchantment level should be changed, as per its default config.
2. Get High Priestess card, and an enchantment. For this example I will be using Protection. The default Apotheosis max level change to Protection is that Protection goes up to Protection 8.
3. Put enchanted book in hand, and see that the enchantment level stops at Protection 4, the default vanilla limit. What I expected to occur is that the book continues upgrading until it hits level 8.

**Additional info:**
NIL.

**Comment by shiroroku** [comment]
https://github.com/shiroroku/TarotCards/commit/ce772664595e3d25fbf51b58bb0aac6712fc7ff8

putting out a quick solution that lets you go above vanilla levels with a config option. maybe one day ill be able to add direct integration into apotheosis but currently it doesnt look like i can.
