### ISSUE TITLE
no were too be found

### ISSUE THREAD

**Issue by GreenForzeGaming** [shiroroku/TarotCards#8]
i by acsedent made the taort card spawn 1 in 1000 first time we made our world. and we had played allot before i noticed. and then changed it too 1 in 50. but yet i havnt found a single card. so im scared that the onfig only applies the first initial launch and that the change afterwards does nothing...

**Comment by shiroroku** [comment]
you would need to travel out of your generated chunks to find new chests. there's not a way to retroactively change the loot table for already generated chests.
